sudo: true

addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - mysql -u root -e 'GRANT ALL ON `typo3_ci_ft%`.* TO travis@127.0.0.1;'

language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="travis"
    - TYPO3_DATABASE_PASSWORD=""
    - typo3DatabaseName="typo3_ci"
    - typo3DatabaseHost="127.0.0.1"
    - typo3DatabaseUsername="travis"
    - typo3DatabasePassword=""
    - TYPO3_VERSION="~7.6"
  matrix:
    - ELASTICSEARCH_VERSION=5.5.2
    - ELASTICSEARCH_VERSION=5.5.1
    - ELASTICSEARCH_VERSION=5.5.0

    - ELASTICSEARCH_VERSION=5.4.3
    - ELASTICSEARCH_VERSION=5.4.2
    - ELASTICSEARCH_VERSION=5.4.1
    - ELASTICSEARCH_VERSION=5.4.0

    - ELASTICSEARCH_VERSION=5.3.3
    - ELASTICSEARCH_VERSION=5.3.2
    - ELASTICSEARCH_VERSION=5.3.1
    - ELASTICSEARCH_VERSION=5.3.0

    - ELASTICSEARCH_VERSION=5.2.2
    - ELASTICSEARCH_VERSION=5.2.1
    - ELASTICSEARCH_VERSION=5.2.0

matrix:
  fast_finish: true

services:
  - mysql

install:
  - curl -O "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ELASTICSEARCH_VERSION.deb" && sudo dpkg -i --force-confnew "elasticsearch-$ELASTICSEARCH_VERSION.deb" && sudo service elasticsearch start
  - make install

script:
  - make unitTests
  - make functionalTests

after_script:
  - make uploadCodeCoverage
  - make clean

cache:
  directories:
    - $HOME/.composer/cache
